FROM alpine:latest

ADD  icloud_photos_downloader /code

RUN set -xe && \
    apk add --no-cache python3 && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --upgrade pip setuptools && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && \
    pip install -e /code && \
    rm -r /root/.cache

RUN adduser -D -h /home/user -u 1000 user
USER user
